routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth/login');
});

Auth::routes();

Route::get('/home', 'EmployeeController@index')->name('home');
Route::resource('employee','EmployeeController');
Route::post('city-by-country','EmployeeController@getCity');

Auth::routes();
Route::get('auth/google', 'Auth\GoogleController@redirectToGoogle');
Route::get('auth/google/callback', 'Auth\GoogleController@handleGoogleCallback');

app/Employee.php
<?php

namespace App;
use App\EducationList;
use App\CountryList;
use App\CityList;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
	use SoftDeletes;

	protected $table = 'employees';
	protected $fillable = ['name','email','address','dob','education_id','city_id','country_id','status','profile_picture','pincode'];
	protected $dates = ['deleted_at'];



	public function getEmployeeDetails($id = ''){

		 $employeeDetails =  Employee::select('id','name','email','address','dob','education_id','city_id','country_id','status','profile_picture','pincode')->with('educationInfo:id,name')->with('countryInfo:id,name')->with('cityInfo:id,name');
		 if(!empty($id)){
		 	return $employeeDetails = $employeeDetails->where('id',$id)->first();	
		 }else{

		 return $employeeDetails = $employeeDetails->get(); 
		 }
	}

	public function educationInfo(){
		return $this->hasOne('App\EducationList', 'id', 'education_id');
	}	

	public function countryInfo(){
		return $this->hasOne('App\CountryList', 'id', 'country_id');
	}
	public function cityInfo(){
		return $this->hasOne('App\CityList', 'id', 'city_id');
	}
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Employee;
use Illuminate\Http\Request;
use App\EducationList;
use App\CountryList;
use App\CityList;
use URL;
use Socialite;
use Google_Client;
use Google_Service_Directory;
use Config;
use Auth;



class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
        $this->employees = new Employee();
    }        
    protected const ACTIVE_FLAG = 1;

    public function index()
    { 
        $data['EmployeeList'] = $this->employees->getEmployeeDetails();
        $data['imageBaseUrl'] = URL::to('/images/');       
        return view('employees.index',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $educationList = EducationList::where('status',self::ACTIVE_FLAG)->select('id','name')->get();
        $countryList = CountryList::where('status',self::ACTIVE_FLAG)->select('id','name')->get();
       return view('employees.create',compact('educationList','countryList'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    { 
        $validated = $request->validate([
            'name' => 'required','email' => 'required','address' => 'required','dob' => 'required','education_id' => 'required','city_id' => 'required','status' => 'required','profile_image' => 'required','pincode' => 'required'
        ]);
        
            
        if ($request->hasFile('profile_image')) {
            $image = $request->file('profile_image');
            $name = time().'.'.$image->getClientOriginalExtension();
            $destinationPath = public_path('/images');
            if($image->move($destinationPath, $name)){  
                $request['profile_picture'] =  $name;
            }
        }

       if(Employee::create($request->all())){
            return response()->json(array('status'=>true,'message'=>'Employee Added'));
       }else{
            return response()->json(array('status'=>false,'message'=>'something went wrong'));

       }
       
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function show(Employee $employee)
    {
        $data['employeeList'] = $this->employees->getEmployeeDetails($employee->id);
        $data['educationList'] = EducationList::where('status',self::ACTIVE_FLAG)->select('id','name')->get();
        $data['countryList'] = CountryList::where('status',self::ACTIVE_FLAG)->select('id','name')->get();
        $data['cityList'] = CityList::where('status',self::ACTIVE_FLAG)->select('id','name')->get();
          $data['imageBaseUrl'] = URL::to('/images/'); 
        return view('employees.view',compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function edit(Employee $employee)
    {

        $data['employeeList'] = $this->employees->getEmployeeDetails($employee->id);

        $data['educationList'] = EducationList::where('status',self::ACTIVE_FLAG)->select('id','name')->get();
        $data['countryList'] = CountryList::where('status',self::ACTIVE_FLAG)->select('id','name')->get();
        $data['cityList'] = CityList::where('status',self::ACTIVE_FLAG)->where('country_id',$data['employeeList']->country_id)->select('id','name')->get();
        $data['imageBaseUrl'] = URL::to('/images/'); 
        return view('employees.update',compact('data'));
      

        }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Employee $employee)
    { 
        $validated = $request->validate([
            'name' => 'required','email' => 'required','address' => 'required','dob' => 'required','education_id' => 'required','city_id' => 'required','status' => 'required','pincode' => 'required'
        ]);

        if ($request->hasFile('profile_image')) {
            $image = $request->file('profile_image');
            $name = time().'.'.$image->getClientOriginalExtension();
            $destinationPath = public_path('/images');
            if($image->move($destinationPath, $name)){  
                $request['profile_picture'] =  $name;
            }
        }
        
        $input = $request->all();
        $resr = $employee->fill($input)->save(); 
        if($employee->fill($input)->save()){
            return response()->json(array('status'=>true,'message'=>'Employee Updated'));
       }else{
            return response()->json(array('status'=>false,'message'=>'something went wrong'));

       }
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function destroy(Employee $employee)
    {


      if(Employee::find($employee->id)->delete()){
        return response()->json(array('status'=>true,'message'=>'Employee Deleted'));

      }else{
        return response()->json(array('status'=>false,'message'=>'something went wrong'));

      }
    }
    //Get city based on country id 
    public function getCity(Request $request){
        if(isset($request['country_id']) && !empty($request['country_id'])){
            $data = CityList::where('country_id',$request->input('country_id'))->select('id','name')->where('status',self::ACTIVE_FLAG)->get();
             return response()->json($data);
        }
    }
   
}

resources/views/employees/create.blade.php
@extends('employees.layout')
  
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Add New Employee</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('employee.index') }}"> Back</a>
        </div>
    </div>
</div>
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
   
<form action="{{ route('employee.store') }}" id= "createForm" method="POST">
    @csrf
  
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                <input type="text" name="name" class="form-control" placeholder="Name" required>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Email:</strong>
                <input type="email" name="email" class="form-control" placeholder="Email" required>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Address:</strong>
                <textarea class="form-control" style="height:150px" name="address" placeholder="Address" required></textarea>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Pin code:</strong>
                <input type="text" name="pincode" class="form-control" placeholder="Pin Code" required>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>DOB:</strong>
                <input type="date" name="dob" class="form-control" placeholder="Date Of Birth" required>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Education:</strong>
                <select name="education_id" id="education_id" class="form-control" required>
                    <option value="">Select Degree</option>
                 @foreach($educationList as $data)
                    <option value="{{$data->id}}">{{$data->name}}</option>
                @endforeach       
                </select>
                
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Country:</strong>
                <select name="country_id" id="country_id" class="form-control" required>
                    <option value="">Select Country</option>
                 @foreach($countryList as $data)
                    <option value="{{$data->id}}">{{$data->name}}</option>
                @endforeach       
                </select>
                
        </div>
    </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>City:</strong>
                <select name="city_id" id="city_id" class="form-control" required>
                </select>
                
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Profile Picture:</strong>
                <input type="file" name="profile_image" id="profile_image" required accept="image/png, image/gif, image/jpeg">
                
            </div>
        </div>


        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Status:</strong>
                  <input type="radio" id="active" name="status" value="1" class="" required>
  <label for="active">Active</label>
  <input type="radio" id="inactive" name="status" value="0" class="" required>
  <label for="inactive">Inactive</label>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
   
</form>
@endsection

resources/views/employees/index.blade.php
@extends('employees.layout')
 
@section('content')


    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Employees Details</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('employee.create') }}"> Create New Employees</a>
            </div>
        </div>
    </div>
   
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
   
 
  <table id="employeeList" class="display">
    <thead>
        <tr>
            <th>Profile</th>
            <th>Name</th>
            <th>Email</th>
            <th>Address</th>
            <th>PinCode</th>
            <th>Age</th>
            <th>Degree</th>
            <th>City & Country</th>
            <th>Status </th>
            <th>Action </th>
        </tr>
    </thead>
    <tbody>
        @foreach($data['EmployeeList'] as $employeeData)
        <tr>
            <td><a href="{{$data["imageBaseUrl"].'/'. $employeeData->profile_picture}}" target="_blank"><img class="profile_picture" src='{{$data["imageBaseUrl"].'/'. $employeeData->profile_picture}}'></td>
            <td></a>{{$employeeData->name}}</td>
            <td>{{$employeeData->email}}</td>
            <td>{{$employeeData->address}}</td>
            <td>{{$employeeData->pincode}}</td>
            <td> @php  $age = (date('Y') - date('Y',strtotime($employeeData->dob)));@endphp {{$age}}</td>
            <td>{{$employeeData['educationInfo']['name']}}</td>
            <td>{{$employeeData['cityInfo']['name'] .'-'. $employeeData['countryInfo']['name']}} </td>
            <td>{{ ($employeeData->status == 1) ? 'Active': 'Inactive'  }}</td>
            <td>
        <a href="employee/{{$employeeData->id}}" class="btn btn-primary a-btn-slide-text">
        <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
    </a>
       <a href="employee/{{$employeeData->id.'/edit'}}" class="btn btn-primary a-btn-slide-text">
        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
    </a>
    <span class="btn btn-primary a-btn-slide-text delete_data"  data-id="{{$employeeData->id}}">
       <span class="glyphicon glyphicon-remove " aria-hidden="true"></span>
    </span>

        </tr>
       @endforeach
    </tbody>
</table>

      
@endsection

resources/views/employees/layout.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Employee Details</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css" rel="stylesheet">
    <meta name="csrf-token" content="{{ csrf_token() }}" />

    <style type="text/css">
    	img.profile_picture {
    		width: 50px;
    		padding-right: 5px;
		}

    </style>
</head>
<body style="background-color: #edf7ef">
  
<div class="container">
    <br/>
    <br/>
    <br/>
    @yield('content')
</div>
   
</body>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js" type="text/javascript"></script>
<script type="text/javascript" src="{{ URL::asset('js/custom.js') }}"></script>

</html>

resources/views/employees/update.blade.php
@extends('employees.layout')
  
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Update Employee</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('employee.index') }}"> Back</a>
        </div>
    </div>
</div>
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
   
<form action="{{ route('employee.update',$data['employeeList']['id']) }}" id= "createForm" method="POST">
    @csrf
  <input type="hidden" name="_method" value="PATCH" autocomplete="off">
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                <input type="text" name="name" class="form-control" placeholder="Name" value="{{$data['employeeList']['name']}}" required>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Email:</strong>
                <input type="email" name="email" class="form-control" placeholder="Email" value="{{$data['employeeList']['email']}}" required>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Address:</strong>
                <textarea class="form-control" style="height:150px" name="address" placeholder="Address" required>{{$data['employeeList']['address']}}</textarea>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Pin code:</strong>
                <input type="text" name="pincode" class="form-control" placeholder="Pin Code" value="{{$data['employeeList']['pincode']}}" required>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>DOB:</strong>
                <input type="date" name="dob" class="form-control" placeholder="Date Of Birth" value="{{$data['employeeList']['dob']}}" required>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Education:</strong>
                <select name="education_id" id="education_id" class="form-control" required>
                    <option value="">Select Degree</option>
                 @foreach($data['educationList'] as $dataInfo)
                    @if($dataInfo->id == $data['employeeList']['education_id'])
                        <option selected value="{{$dataInfo->id}}">{{$dataInfo->name}}</option>
                    @else
                        <option value="{{$dataInfo->id}}">{{$dataInfo->name}}</option>
                    @endif
                @endforeach       
                </select>
                
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Country:</strong>
                <select name="country_id" id="country_id" class="form-control" required>
                    <option value="">Select Country</option>
                 @foreach($data['countryList'] as $dataInfo)
                     @if($dataInfo->id == $data['employeeList']['country_id'])
                        <option selected value="{{$dataInfo->id}}">{{$dataInfo->name}}</option>
                    @else
                        <option value="{{$dataInfo->id}}">{{$dataInfo->name}}</option>
                    @endif
                @endforeach       
                </select>
                
        </div>
    </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>City:</strong>
                <select name="city_id" id="city_id" class="form-control" required>
                    <option value="">Select City</option>
                    @foreach($data['cityList'] as $dataInfo)
                        @if($dataInfo->id == $data['employeeList']['city_id'])
                            <option selected value="{{$dataInfo->id}}">{{$dataInfo->name}}</option>
                        @else
                            <option value="{{$dataInfo->id}}">{{$dataInfo->name}}</option>
                        @endif
                @endforeach 
                </select>
                
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Profile Picture:</strong>
            <a href = "{{$data['imageBaseUrl'].'/'.$data['employeeList']['profile_picture']}}" target="_blank"><img class= "profile_picture" src ="{{$data['imageBaseUrl'].'/'.$data['employeeList']['profile_picture']}}"></a>  
                          <input type="file" name="profile_image" id="profile_image" value="{{$data['employeeList']['profile_picture']}}" accept="image/png, image/gif, image/jpeg">
                
            </div>
        </div>


        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Status:</strong>
                  <input type="radio" id="active" name="status" value="1" {{($data['employeeList']['status'] == 1)? 'Checked':''}} required>
  <label for="active">Active</label>
  <input type="radio" id="inactive" name="status" value="0" {{($data['employeeList']['status'] == 0)? 'Checked':''}} required>
  <label for="inactive">Inactive</label>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
   
</form>
@endsection

resources/views/employees/view.blade.php
@extends('employees.layout')
  
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Employee Details</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('employee.index') }}"> Back</a>
        </div>
    </div>
</div>
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
   
<form action="{{ route('employee.update',$data['employeeList']['id']) }}" id= "createForm" method="PUT">
    @csrf
  
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                <input type="text" name="name" class="form-control" placeholder="Name" value="{{$data['employeeList']['name']}}" readonly>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Email:</strong>
                <input type="text" name="email" class="form-control" placeholder="Email" value="{{$data['employeeList']['email']}}" readonly>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Address:</strong>
                <textarea class="form-control" style="height:150px" name="address" placeholder="Address" readonly>{{$data['employeeList']['address']}}</textarea>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Pin code:</strong>
                <input type="text" name="pincode" class="form-control" placeholder="Pin Code" value="{{$data['employeeList']['pincode']}}" readonly>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>DOB:</strong>
                <input type="date" name="dob" class="form-control" placeholder="Date Of Birth" value="{{$data['employeeList']['dob']}}" readonly>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Education:</strong>
                <select name="education_id" id="education_id" class="form-control" readonly>
                    <option value="">Select Degree</option>
                 @foreach($data['educationList'] as $dataInfo)
                    @if($dataInfo->id == $data['employeeList']['education_id'])
                        <option selected value="{{$dataInfo->id}}">{{$dataInfo->name}}</option>
                    @else
                        <option value="{{$dataInfo->id}}">{{$dataInfo->name}}</option>
                    @endif
                @endforeach       
                </select>
                
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Country:</strong>
                <select name="country_id" id="country_id" class="form-control" readonly>
                    <option value="">Select Country</option>
                 @foreach($data['countryList'] as $dataInfo)
                     @if($dataInfo->id == $data['employeeList']['country_id'])
                        <option selected value="{{$dataInfo->id}}">{{$dataInfo->name}}</option>
                    @else
                        <option value="{{$dataInfo->id}}">{{$dataInfo->name}}</option>
                    @endif
                @endforeach       
                </select>
                
        </div>
    </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>City:</strong>
                <select name="city_id" id="city_id" class="form-control" readonly>
                    <option value="">Select City</option>
                    @foreach($data['cityList'] as $dataInfo)
                        @if($dataInfo->id == $data['employeeList']['city_id'])
                            <option selected value="{{$dataInfo->id}}">{{$dataInfo->name}}</option>
                        @else
                            <option value="{{$dataInfo->id}}">{{$dataInfo->name}}</option>
                        @endif
                @endforeach 
                </select>
                
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Profile Picture:</strong>
                <img class= "profile_picture" src ="{{$data['imageBaseUrl'].'/'.$data['employeeList']['profile_picture']}}">
                <a href = "{{$data['imageBaseUrl'].'/'.$data['employeeList']['profile_picture']}}" target="_blank"><img class= "profile_picture" src ="{{$data['imageBaseUrl'].'/'.$data['employeeList']['profile_picture']}}"> </a> 
                 
                          
            </div>
        </div>


        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Status:</strong>
                  <input readonly type="radio" id="active" name="status" value="1" {{($data['employeeList']['status'] == 1)? 'Checked':''}}>
  <label for="active">Active</label>
  <input readonly type="radio" id="inactive" name="status" value="0" {{($data['employeeList']['status'] == 0)? 'Checked':''}}>
  <label for="inactive">Inactive</label>
            </div>
        </div>
       
    </div>
   
</form>
@endsection